spring:
  application:
    name: demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    name: rabbitmq_queue
  exchange:
    name: rabbitmq_exchange
  routing:
    key: rabbitmq_routing_key
server:
  port: 8091
